services:
  app:
    image: mgcheon/final-eureka:latest
    container_name: eureka-service
    env_file:
      - /home/eureka-server/.env  # .env 파일에서 환경 변수를 로드
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
