services:
  app:
    image: mgcheon/final-config:latest
    container_name: config-service
    env_file:
      - /home/config-server/.env  # .env 파일에서 환경 변수를 로드
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
