services:
  app:
    image: mgcheon/final-room:latest
    container_name: room-service
    env_file:
      - /home/room-server/.env  # .env 파일에서 환경 변수를 로드
    ports:
      - 8085:8085
    networks:
      - service-network

  redis:
    image: redis:latest
    container_name: room-redis
    ports:
      - 6380:6380
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
