services:
  app:
    image: mgcheon/final-accommodation:latest
    container_name: accommodation-service
    env_file:
      - /home/accommodation-service/.env  # .env 파일에서 환경 변수를 로드
    ports:
      - 8081:8081
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
