server:
  port: ${EUREKA_SERVER_PORT}

spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA} #Eureka 서버에 등록할지 여부
    fetch-registry: ${EUREKA_FETCH_REGISTRY} #Eureka 서버의 정보를 가져올지 여부
  username: ${EUREKA_USERNAME}
  password: ${ERUEKA_PASSWORD}