server:
  port: ${EUREKA_SERVER_PORT}
eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA} #Eureka 서버에 등록할지 여부
    fetch-registry: ${EUREKA_FETCH_REGISTRY} #Eureka 서버의 정보를 가져올지 여부
