server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: ${CONFIG_APP_NAME}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          ignore-local-ssh-settings: ${CONFIG_GIT_IGNORE_LOCAL_SSH_SETTING}
          private-key: ${CONFIG_GIT_PRIVATE_KEY}
config:
  username: ${CONFIG_USERNAME}
  password: ${CONFIG_PASSWORD}