server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: ${CONFIG_APP_NAME}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          search-paths: config-file/**
          default-label: main
          ignore-local-ssh-settings: ${CONFIG_GIT_IGNORE_LOCAL_SSH_SETTING}
          privateKey: |
            -----BEGIN EC PRIVATE KEY-----
            
            -----END EC PRIVATE KEY-----
          host-key: ${GIT_HOST_KEY}
          host-key-algorithm: ${GIT_HOST_ALGORITHM}
#          clone-on-start: true
config:
  username: ${CONFIG_USERNAME}
  password: ${CONFIG_PASSWORD}