server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: ${CONFIG_APP_NAME}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
config:
  username: ${CONFIG_USERNAME}
  password: ${CONFIG_PASSWORD}