server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: ${CONFIG_APP_NAME}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          search-paths: config-file/**
          default-label: main
          ignore-local-ssh-settings: ${CONFIG_GIT_IGNORE_LOCAL_SSH_SETTING}
          private-key: ${CONFIG_GIT_PRIVATE_KEY}
#          username: ${GITHUB_USERNAME}
#          password: ${GITHUB_PASSWORD}
config:
  username: ${CONFIG_USERNAME}
  password: ${CONFIG_PASSWORD}