name: config server CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "config-server/**"
      - ".github/workflows/config*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew :config-server:build -x test

      # Docker 이미지 build
      - name: docker image build
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_CONFIG_IMAGE_NAME}}  -f config-server/Dockerfile config-server/

      # DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      # DockerHub push
      - name: docker Hub push
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_CONFIG_IMAGE_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Decode SSH Private Key
        id: decode_key
        run: |
          echo "${{ secrets.CONFIG_GIT_PRIVATE_KEY }}" | base64 -d > git_private_key
          chmod 600 git_private_key

      - name: Copy SSH Key to Ubuntu Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "git_private_key"
          target: "/home/config-server"

      - name: Delete .env and docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            cd /home/config-service/
            rm -f .env
            rm -f docker-compose.yml

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "./config-server/docker-compose.yml"
          target: "/home"

      - name: set environment variables
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            echo "CONFIG_SERVER_PORT=${{secrets.CONFIG_SERVER_PORT}}" >> /home/config-server/.env
            echo "CONFIG_APP_NAME=${{secrets.CONFIG_APP_NAME}}" >> /home/config-server/.env
            echo "CONFIG_GIT_URI=${{secrets.CONFIG_GIT_URI}}" >> /home/config-server/.env
            echo "CONFIG_GIT_IGNORE_LOCAL_SSH_SETTING=$(cat git_private_key)" >> /home/config-server/.env
            echo "CONFIG_GIT_IGNORE_LOCAL_SSH_SETTING=${{secrets.CONFIG_GIT_IGNORE_LOCAL_SSH_SETTING}}" >> /home/config-server/.env
            echo "CONFIG_USERNAME=${{secrets.CONFIG_USERNAME}}" >> /home/config-server/.env
            echo "CONFIG_PASSWORD=${{secrets.CONFIG_PASSWORD}}" >> /home/config-server/.env

      - name: Deploy application with Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            cd /home/config-server/
            docker-compose down
            docker-compose pull
            docker-compose up -d