name: eureka server CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'eureka-server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew :eureka-server:build -x test

      # Docker 이미지 build
      - name: docker image build
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_EUREKA_IMAGE_NAME}}  -f eureka-server/Dockerfile eureka-server/

      # DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      # DockerHub push
      - name: docker Hub push
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_EUREKA_IMAGE_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set environment variables
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            echo "EUREKA_SERVER_PORT=${{secrets.EUREKA_SERVER_PORT}}" >> /home/eureka-server/.env
            echo "EUREKA_CLIENT_REGISTER_WITH_EUREKA=${{secrets.EUREKA_CLIENT_REGISTER_WITH_EUREKA}}" >> /home/eureka-server/.env
            echo "EUREKA_FETCH_REGISTRY=${{secrets.EUREKA_FETCH_REGISTRY}}" >> /home/eureka-server/.env
            echo "EUREKA_USERNAME=${{secrets.EUREKA_USERNAME}}" >> /home/eureka-server/.env
            echo "EUREKA_PASSWORD=${{secrets.EUREKA_PASSWORD}}" >> /home/eureka-server/.env


      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "./eureka-server/docker-compose.yml"
          target: "/home"

      - name: Deploy application with Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            cd /home/eureka-server/
            docker-compose down
            docker-compose pull
            docker-compose up -d