name: room service CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'room-service/**'
      - ".github/workflows/room*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 [corretto(Oracle)]
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle [--parallel]
        run: ./gradlew :room-service:build -x test