name: room server CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'room-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew :room-service:build -x test

      # Docker 이미지 build
      - name: docker image build
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_ROOM_IMAGE_NAME}}  -f room-service/Dockerfile room-service/

      # DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      # DockerHub push
      - name: docker Hub push
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_ROOM_IMAGE_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete .env and docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            cd /home/room-service/
            rm -f .env
            rm -f docker-compose.yml

      - name: set environment variables
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            echo "ROOM_APP_NAME=${{secrets.ROOM_APP_NAME}}" >> /home/room-service/.env
            echo "APP_PROFILE=${{secrets.APP_PROFILE}}" >> /home/room-service/.env
            echo "CONFIG_SERVER_URI=${{secrets.CONFIG_SERVER_URI}}" >> /home/room-service/.env
            echo "ROOM_REGISTER_WITH_EUREKA=${{secrets.ROOM_REGISTER_WITH_EUREKA}}" >> /home/room-service/.env
            echo "ROOM_EUREKA_FETCH_REGISTRY=${{secrets.ROOM_EUREKA_FETCH_REGISTRY}}" >> /home/room-service/.env
            echo "EUREKA_SERVER_URI=${{secrets.EUREKA_SERVER_URI}}" >> /home/room-service/.env

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: "./room-service/docker-compose.yml"
          target: "/home"

      - name: Deploy application with Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            cd /home/room-service/
            docker-compose down
            docker-compose pull
            docker-compose up -d